### ISSUE TITLE
Using ActiveRecord and Mongoid side by side is not possible

### ISSUE THREAD

**Issue by tmichel** [activerecord-hackery/ransack#499]
In our application we talk to different databases (namely PostgreSQL via ActiveRecord and mongodb via Mongoid).

The way adapters are structured renders ransack unusable with ActiveRecord when both gems are loaded. Adapters monkey patch base ransack classes to provide the specific behaviour needed. Mongoid is loaded last so that works, but nothing else. 

There is a minimal test-case for reproducing this: [link to gist][1]

[1]: https://gist.github.com/tmichel/94f33dca318b31dbdeb5

**Comment by RobWu** [comment]
Same problem here..

**Comment by RobWu** [comment]
The problem might be this lines: 
```ruby
if defined?(::Mongoid)
  require 'ransack/adapters/mongoid/ransack/constants'
else
  require 'ransack/adapters/active_record/ransack/constants'
end
```
https://github.com/activerecord-hackery/ransack/blob/master/lib/ransack.rb#L5-L9

**Comment by tmichel** [comment]
There are more places where these are conditionally required. Or just required overwriting other adapters.

* [lib/ransack/nodes.rb](https://github.com/activerecord-hackery/ransack/blob/c5308a53dc448261ddb4b19123662ea8070d32df/lib/ransack/nodes.rb)
* [lib/ransack/search.rb](https://github.com/activerecord-hackery/ransack/blob/c5308a53dc448261ddb4b19123662ea8070d32df/lib/ransack/search.rb)
* [lib/ransack/search.rb](https://github.com/activerecord-hackery/ransack/blob/c5308a53dc448261ddb4b19123662ea8070d32df/lib/ransack/search.rb)

**Comment by remon** [comment]
how did you solve these problem ,I am facing it now too?

**Comment by tmichel** [comment]
@remon I haven't solved this. I had to pin the version to the last working one (1.5.1 in my case).
IMO all the adapter related code has to be rewritten so it doesn't use monkey patching and can be loaded side by side.

**Comment by jonatack** [comment]
Hm... perhaps the easiest solution would be to change the conditionals that check for Mongoid, to check for defined?(::Mongoid) && !defined?(::ActiveRecord).

Personally, I don't use Mongoid and so I don't maintain the Mongoid adapter. Anything related to Mongoid here needs to be maintained by someone who does use it, and if that doesn't happen on a regular basis, we may have to consider removing Mongoid from master out to a separate branch.

**Comment by jonatack** [comment]
Hm... perhaps the easiest solution would be to change the conditionals that check for Mongoid, to check for defined?(::Mongoid) && !defined?(::ActiveRecord)... which would at least allow have both defined and using Ransack for Active Record. And maybe DRY the conditionals in one place. 

Personally, I don't use Mongoid and so I don't maintain the Mongoid adapter. Anything related to Mongoid here needs to be maintained by someone who does use it, and if that doesn't happen on a regular basis, we may have to consider removing Mongoid from master out to a separate branch.

**Comment by Robert-Christopher** [comment]
I just encountered this issue, do we have any work-around for this ? Looks like patching will require a re-write on a lot of files as pointed by @tmichel above

**Comment by jonatack** [comment]
This should be fixed by #541.

**Comment by ogerman** [comment]
But it's still can't be used with both adapters, and condition still present here.
https://github.com/activerecord-hackery/ransack/blob/master/lib/ransack/adapters.rb#L7

**Comment by jonatack** [comment]
Using Active Record and Mongoid side by side is possible, in which case Ransack loads the AR adapter.  Ransack does not load both adapters.

I'd be happy to look at your PR to run both adapters at the same time, if it's important to you. Please remember that none of the Ransack maintainers use Mongo DB, and that the PR to add the Mongoid adapter was accepted with the caveat that the community of Ransack's Mongoid users maintain it :wink:
